/*
 * File: app/store/Fragen.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HSK.store.Fragen', {
    extend: 'Ext.data.Store',

    requires: [
        'HSK.model.Frage',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    config: {
        data: [
            {
                C: 1,
                Nr: 1,
                Q: 'Welches Tier ist der Urahn des heutigen Hundes?',
                A: ''
            },
            {
                C: 1,
                Nr: 1,
                Q: '',
                A: 'A.  Der Goldschakal.'
            },
            {
                C: 1,
                Nr: 1,
                Q: '',
                A: 'B.  Der Wolf.',
                correct: true
            },
            {
                C: 1,
                Nr: 1,
                Q: '',
                A: 'C.  Der Kojote.'
            },
            {
                C: 1,
                Nr: 1,
                Q: '',
                A: 'D.  Der Dingo.'
            },
            {
                C: 1,
                Nr: 14,
                Q: 'Bis zu welchem Alter bezeichnet man Hunde als „Welpen”?',
                A: ''
            },
            {
                C: 1,
                Nr: 14,
                Q: '',
                A: 'A.  Bis zu einem Jahr.'
            },
            {
                C: 1,
                Nr: 14,
                Q: '',
                A: 'B.  Von Geburt an bis zum Abschluss der Prägephase (Sozialisationsphase), also ca. bis zum Abschluss des 4. Lebensmonats.'
            },
            {
                C: 1,
                Nr: 14,
                Q: '',
                A: 'C.  Bis zur Geschlechtsreife.'
            },
            {
                C: 1,
                Nr: 14,
                Q: '',
                A: 'D.  Bis sie nicht mehr gesäugt werden.'
            },
            {
                C: 1,
                Nr: 32,
                Q: 'Woran kann man erkennen, ob sich ein Hund einem anderen gegenüber dominant verhält?',
                A: ''
            },
            {
                C: 1,
                Nr: 32,
                Q: '',
                A: 'A.  Er legt sich auf die Seite und wedelt.'
            },
            {
                C: 1,
                Nr: 32,
                Q: '',
                A: 'B.  Er macht sich groß (Schwanz hoch, Ohren nach vorne, steifer Gang) und weicht Blickkontakt nicht aus.'
            },
            {
                C: 1,
                Nr: 32,
                Q: '',
                A: 'C.  Er bellt und legt die Ohren an.'
            },
            {
                C: 1,
                Nr: 32,
                Q: '',
                A: 'D.  Er legt die Schnauze oder Pfote auf den Rücken des anderen Hundes.'
            },
            {
                C: 1,
                Nr: 50,
                Q: 'Wer wäre der beste Ansprechpartner, wenn es zu Problemen im Zusammenleben kommt?',
                A: ''
            },
            {
                C: 1,
                Nr: 50,
                Q: '',
                A: 'A.  Der Züchter oder ein anderer Halter derselben Rasse.'
            },
            {
                C: 1,
                Nr: 50,
                Q: '',
                A: 'B.  Ein Tierarzt, der sich auf Verhalten spezialisiert hat.'
            },
            {
                C: 1,
                Nr: 50,
                Q: '',
                A: 'C.  Ein anderer Hundebesitzer, der seinen Hund gut unter Kontrolle hat.'
            },
            {
                C: 1,
                Nr: 50,
                Q: '',
                A: 'D.  Ein moderner und erfahrener Hundetrainer, der im Bereich Problemverhalten speziell geschult ist.'
            },
            {
                C: 1,
                Nr: 68,
                Q: 'Ihr frei laufender Hund kommt auf Ihr Rufen nicht zurück. Was kann man tun?',
                A: ''
            },
            {
                C: 1,
                Nr: 68,
                Q: '',
                A: 'A.  Sich so verstecken, dass man den Hund noch sehen kann und den Hund dann nach einiger Zeit aus dem Versteck heraus noch einmal rufen. Außerdem einen Gehorsamskurs buchen, denn das Rückrufkommando sollte klappen.'
            },
            {
                C: 1,
                Nr: 68,
                Q: '',
                A: 'B.  Schnell in die entgegengesetzte Richtung davonrennen und sich so für den Hund interessant machen. Außerdem schnellstmöglich Rat einholen bei einem erfahrenen und modernen Hundeausbilder, der Hunde über positive Trainingstechniken erzieht.'
            },
            {
                C: 1,
                Nr: 68,
                Q: '',
                A: 'C.  Versuchen, den Hund einzufangen. Solch einen Hund kann man nie wieder ableinen.'
            },
            {
                C: 1,
                Nr: 68,
                Q: '',
                A: 'D.  Den Hund laut anschreien und mit Strafen drohen, damit er Angst bekommt und herankommt. Wenn der Hund schon älter ist, kann man nichts mehr machen.'
            },
            {
                C: 2,
                Nr: 79,
                Q: 'Was kann passieren, wenn man einen Hund als Erziehungsmaßnahme häufig und hart bestraft?',
                A: ''
            },
            {
                C: 2,
                Nr: 79,
                Q: '',
                A: 'A.  Er wird die Übung schnell und zuverlässig ausführen, denn so lernt er, dass er brav sein muss.'
            },
            {
                C: 2,
                Nr: 79,
                Q: '',
                A: 'B.  Er kann scheu und unsicher werden, weil er kein Vertrauen mehr zu seinem Besitzer hat.'
            },
            {
                C: 2,
                Nr: 79,
                Q: '',
                A: 'C.  Es passiert nichts Schlimmes. Hunde untereinander verhalten sich auch rigoros. Der Hund wird also große Freude bei den Übungen haben, wenn er erst verstanden hat, worum es geht.'
            },
            {
                C: 2,
                Nr: 79,
                Q: '',
                A: 'D.  Er könnte unter Umständen aggressiv reagieren, weil er sich bedroht fühlt.'
            },
            {
                C: 2,
                Nr: 106,
                Q: 'Auf dem Hundespaziergang kommt einem ein Reiter entgegen. Wie soll man sich verhalten?',
                A: ''
            },
            {
                C: 2,
                Nr: 106,
                Q: '',
                A: 'A.  Wenn der Hund Pferde kennt, braucht man nichts zu unternehmen, denn dann hat der Hund keine Angst.'
            },
            {
                C: 2,
                Nr: 106,
                Q: '',
                A: 'B.  Man sollte den Hund heranrufen und an die Leine nehmen, bis Pferd und Reiter vorbei sind und man sicher weiß, dass der Hund nicht hinterherrennen wird.'
            },
            {
                C: 2,
                Nr: 106,
                Q: '',
                A: 'C.  Wenn der Reiter nur ”Schritt” reitet, ist keine Gefahr gegeben, denn das langsame Reiten verleitet nicht zum Jagen.'
            },
            {
                C: 2,
                Nr: 106,
                Q: '',
                A: 'D.  Man sollte seinen Hund grundsätzlich unter Kontrolle nehmen, da manche Pferde auch bei ruhigen und freundlichen Hunden ängstlich reagieren und dadurch Unfälle entstehen können.'
            },
            {
                C: 2,
                Nr: 123,
                Q: 'Sollte man, wenn man einen Hund übernimmt, mit dem Hund zum Tierarzt gehen, auch wenn der Hund einen gesunden Eindruck macht?',
                A: ''
            },
            {
                C: 2,
                Nr: 123,
                Q: '',
                A: 'A.  Ja, damit der Tierarzt anhand des Impfpasses überprüfen kann, ob der Hund ausreichend geimpft ist.'
            },
            {
                C: 2,
                Nr: 123,
                Q: '',
                A: 'B.  Ja, damit sich der Hund an den Tierarzt und die Abläufe in der Praxis gewöhnt.'
            },
            {
                C: 2,
                Nr: 123,
                Q: '',
                A: 'C.  Nein, so etwas ist nicht notwendig und reine Geldverschwendung.'
            },
            {
                C: 2,
                Nr: 123,
                Q: '',
                A: 'D.  Ja, damit der Tierarzt den Hund möglichst auch einmal gesund kennen lernen kann. Er kann dann krankheitsbedingtes Verhalten besser einordnen.'
            },
            {
                C: 2,
                Nr: 151,
                Q: 'Warum ist es wichtig, seinen Hund regelmäßig gegen Tollwut impfen zu lassen?',
                A: ''
            },
            {
                C: 2,
                Nr: 151,
                Q: '',
                A: 'A.  Die Tollwutimpfung ist gesetzlich vorgeschrieben.'
            },
            {
                C: 2,
                Nr: 151,
                Q: '',
                A: 'B.  Tollwut ist eine Infektionskrankheit, mit der sich auch Menschen infizieren können.'
            },
            {
                C: 2,
                Nr: 151,
                Q: '',
                A: 'C.  Eine Tollwutimpfung ist überflüssig Tollwut kommt in Deutschland überhaupt nicht mehr vor.'
            },
            {
                C: 2,
                Nr: 151,
                Q: '',
                A: 'D.  Tollwutgeimpfte Hunde stehen gesetzlich besser da als ungeimpfte.'
            },
            {
                C: 2,
                Nr: 162,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 2,
                Nr: 162,
                Q: '',
                A: 'A. Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 2,
                Nr: 162,
                Q: '',
                A: 'B. Der Hund ist ängstlich'
            },
            {
                C: 2,
                Nr: 162,
                Q: '',
                A: 'C. Der Hund droht selbstsicher.'
            },
            {
                C: 2,
                Nr: 162,
                Q: '',
                A: 'D. Der Hund ist unterwürfig'
            },
            {
                C: 3,
                Nr: 2,
                Q: 'Sind alle Hunde gleich oder gibt es rassetypische Eigenschaften?',
                A: ''
            },
            {
                C: 3,
                Nr: 2,
                Q: '',
                A: 'A.  Alle Hunde sind gleich.'
            },
            {
                C: 3,
                Nr: 2,
                Q: '',
                A: 'B.  Je nach Rasse weisen die Hunde unterschiedliche Veranlagungen auf.'
            },
            {
                C: 3,
                Nr: 2,
                Q: '',
                A: 'C.  Verschiedene Rassen unterscheiden sich nur durch ihr äußeres Erscheinungsbild.'
            },
            {
                C: 3,
                Nr: 2,
                Q: '',
                A: 'D.  Rassetypische Eigenschaften gibt es nicht, aber anhand der Größe kann man eine Einteilung in ”kinderfreundlich”, ”gefährlich”, ”leicht zu erziehen” etc. treffen.'
            },
            {
                C: 3,
                Nr: 15,
                Q: 'Welche Auswirkung hat häufige und lange Zwingerhaltung auf die Wesensentwicklung des Welpen?',
                A: ''
            },
            {
                C: 3,
                Nr: 15,
                Q: '',
                A: 'A.  So lernt der Hund gut alleine zu bleiben.'
            },
            {
                C: 3,
                Nr: 15,
                Q: '',
                A: 'B.  Defizite im Sozialverhalten gegenüber Menschen und Artgenossen.'
            },
            {
                C: 3,
                Nr: 15,
                Q: '',
                A: 'C.  Probleme im Bereich des häuslichen Sauberkeitstrainings.'
            },
            {
                C: 3,
                Nr: 15,
                Q: '',
                A: 'D.  Die gesundheitliche Widerstandskraft ist größer.'
            },
            {
                C: 3,
                Nr: 33,
                Q: 'Was bedeutet es, wenn ein Hund einem anderen den Kopf auf den Rücken legt?',
                A: ''
            },
            {
                C: 3,
                Nr: 33,
                Q: '',
                A: 'A.  Er ist unterwürfig.'
            },
            {
                C: 3,
                Nr: 33,
                Q: '',
                A: 'B.  Er macht eine Spielaufforderung.'
            },
            {
                C: 3,
                Nr: 33,
                Q: '',
                A: 'C.  Er ist müde.'
            },
            {
                C: 3,
                Nr: 33,
                Q: '',
                A: 'D.  Es ist eine Imponiergeste.'
            },
            {
                C: 3,
                Nr: 51,
                Q: 'Was hat für Hunde die größte Bedeutung im Bereich der Rangfolge.',
                A: ''
            },
            {
                C: 3,
                Nr: 51,
                Q: '',
                A: 'A.  Aufmerksamkeit (Spiel, Futter, Zuwendung) fordern zu können.'
            },
            {
                C: 3,
                Nr: 51,
                Q: '',
                A: 'B.  Täglich mehrmals rausgehen zu dürfen.'
            },
            {
                C: 3,
                Nr: 51,
                Q: '',
                A: 'C.  Einen gemütlichen, ggf. erhöhten Liegeplatz zu haben.'
            },
            {
                C: 3,
                Nr: 51,
                Q: '',
                A: 'D.  Spielzeug zur freien Verfügung zu besitzen.'
            },
            {
                C: 3,
                Nr: 69,
                Q: 'Besteht die Gefahr, durch Strafen einen Hund so zu schockieren, dass er das Vertrauen in einen verliert?',
                A: ''
            },
            {
                C: 3,
                Nr: 69,
                Q: '',
                A: 'A.  Nein, nicht wenn man vorher ein gutes Verhältnis hatte.'
            },
            {
                C: 3,
                Nr: 69,
                Q: '',
                A: 'B.  Ja, bei sensiblen Hunden manchmal sogar mit Kleinigkeiten, besonders wenn die Handlung für den Hund ”unlogisch” ist.'
            },
            {
                C: 3,
                Nr: 69,
                Q: '',
                A: 'C.  Ja, durch inkonsequentes und launisches Vorgehen.'
            },
            {
                C: 3,
                Nr: 69,
                Q: '',
                A: 'D.  Nur bei generell ängstlichen Hunden.'
            },
            {
                C: 4,
                Nr: 80,
                Q: 'Wie häufig und wie lange sollte man mit dem Hund üben?',
                A: ''
            },
            {
                C: 4,
                Nr: 80,
                Q: '',
                A: 'A.  Ein Mal am Tag eine Stunde.'
            },
            {
                C: 4,
                Nr: 80,
                Q: '',
                A: 'B.  So häufig wie es geht, aber immer nur kurz, dann kann sich der Hund am Besten konzentrieren.'
            },
            {
                C: 4,
                Nr: 80,
                Q: '',
                A: 'C.  Es ist besonders wichtig, dass man täglich immer zur selben Zeit übt, wie lange, ist abhängig vom Trainingsstand des Hundes.'
            },
            {
                C: 4,
                Nr: 80,
                Q: '',
                A: 'D.  Zwei Übungen auf jedem Spaziergang sind absolut ausreichend, sonst wird der Hund überfordert.'
            },
            {
                C: 4,
                Nr: 107,
                Q: 'Der eigene Hund ist plötzlich in eine Rauferei verwickelt. Wie sollte man reagieren?',
                A: ''
            },
            {
                C: 4,
                Nr: 107,
                Q: '',
                A: 'A.  Man sollte die raufenden Hunde solange möglichst laut anschreien, bis sie aufhören sich zu raufen.'
            },
            {
                C: 4,
                Nr: 107,
                Q: '',
                A: 'B.  Man sollte sich gar nicht einmischen. Beide Besitzer sollten sich einigen, sich kommentarlos und möglichst zügig in entgegengesetzter Richtung von den Hunden zu entfernen. Die Hunde sollten, sobald sie zum Besitzer kommen, von diesem angeleint werden, um eine mögliche zweite Kampfphase zu vermeiden.'
            },
            {
                C: 4,
                Nr: 107,
                Q: '',
                A: 'C.  Wenn nur zwei Hunde in die Rauferei verwickelt sind, sollte man die Hunde trennen, indem man am Schwanz oder an den Hinterbeinen zieht, und zwar gleichzeitig bei beiden Hunden.'
            },
            {
                C: 4,
                Nr: 107,
                Q: '',
                A: 'D.  Man sollte den Hund, der angegriffen worden ist, hinterher trösten und den anderen streng zurechtweisen und bestrafen.'
            },
            {
                C: 4,
                Nr: 124,
                Q: 'Gibt es Dinge, die man prophylaktisch tun kann, damit der Hund gesund bleibt?',
                A: ''
            },
            {
                C: 4,
                Nr: 124,
                Q: '',
                A: 'A.  Ja. Der Hund sollte z.B. regelmäßig geimpft werden.'
            },
            {
                C: 4,
                Nr: 124,
                Q: '',
                A: 'B.  Ja, man sollte den ganzen Körper z.B. beim Bürsten täglich genau anschauen, um Veränderungen oder Parasitenbefall sofort zu erkennen.'
            },
            {
                C: 4,
                Nr: 124,
                Q: '',
                A: 'C.  Ja, der Hund sollte nur das beste Futter bekommen. Das ist in aller Regel auch das teuerste.'
            },
            {
                C: 4,
                Nr: 124,
                Q: '',
                A: 'D.  Ja, einmal wöchentlich sollte man den Hund baden.'
            },
            {
                C: 4,
                Nr: 152,
                Q: 'Wenn im Mietvertrag kein Hinweis zu finden ist, ob Tierhaltung erlaubt ist, darf man sich dann einen Hund anschaffen?',
                A: ''
            },
            {
                C: 4,
                Nr: 152,
                Q: '',
                A: 'A.  Nein, erst muss man die schriftliche Erlaubnis des Vermieters einholen.'
            },
            {
                C: 4,
                Nr: 152,
                Q: '',
                A: 'B.  Ja, aber nur einen Hund, der kleiner als 40 cm Schulterhöhe ist.'
            },
            {
                C: 4,
                Nr: 152,
                Q: '',
                A: 'C.  Ja, ansonsten müsste ein Haltungsverbot extra erwähnt werden.'
            },
            {
                C: 4,
                Nr: 152,
                Q: '',
                A: 'D.  Nein, man muss erst die Zustimmung der anderen Mieter einholen.'
            },
            {
                C: 4,
                Nr: 163,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 4,
                Nr: 163,
                Q: '',
                A: 'A.  Der Hund ist neutral bis aufmerksam'
            },
            {
                C: 4,
                Nr: 163,
                Q: '',
                A: 'B.  Der Hund droht aus Unsicherheit.'
            },
            {
                C: 4,
                Nr: 163,
                Q: '',
                A: 'C.  Der Hund ist friedfertig.'
            },
            {
                C: 4,
                Nr: 163,
                Q: '',
                A: 'D.  Der Hund ist unterwürfig.'
            },
            {
                C: 5,
                Nr: 3,
                Q: 'Was ist die Grundveranlagung, die jeder Hund in sich trägt?',
                A: ''
            },
            {
                C: 5,
                Nr: 3,
                Q: '',
                A: 'A.  Hunde sind Jagdraubtiere.'
            },
            {
                C: 5,
                Nr: 3,
                Q: '',
                A: 'B.  Hunde sind für das Zusammenleben mit Menschen geschaffen worden. Sie sind völlig abhängig vom Menschen und können alleine nicht existieren, da sie sich keine Nahrung beschaffen könnten.'
            },
            {
                C: 5,
                Nr: 3,
                Q: '',
                A: 'C.  Hunde sind soziale Rudeltiere und darauf ausgerichtet in einem Gruppenverband zu leben.'
            },
            {
                C: 5,
                Nr: 3,
                Q: '',
                A: 'D.  Hunde sind Aasfresser und suchen deshalb ständig nach toten Tieren.'
            },
            {
                C: 5,
                Nr: 16,
                Q: 'Woran erkennen Sie eine empfehlenswerte Welpenspielgruppe?',
                A: ''
            },
            {
                C: 5,
                Nr: 16,
                Q: '',
                A: 'A.  Es dürfen Hunde verschiedener Rassen teilnehmen.'
            },
            {
                C: 5,
                Nr: 16,
                Q: '',
                A: 'B.  Der Trainer bestraft einen Welpen sofort, wenn er aggressives Verhalten zeigt, denn die Hunde sollen eine gute Sozialverträglichkeit lernen.'
            },
            {
                C: 5,
                Nr: 16,
                Q: '',
                A: 'C.  Es dürfen nur gesunde Hunde bis max. zur 16. Lebenswoche teilnehmen.'
            },
            {
                C: 5,
                Nr: 16,
                Q: '',
                A: 'D.  Den Welpen werden viele verschiedene Reizsituationen geboten, damit sie ”umweltsicher” werden.'
            },
            {
                C: 5,
                Nr: 34,
                Q: 'Was bedeutet es, wenn sich zwei Hunde direkt in die Augen starren?',
                A: ''
            },
            {
                C: 5,
                Nr: 34,
                Q: '',
                A: 'A.  Es bedeutet, dass sie sich gern haben.'
            },
            {
                C: 5,
                Nr: 34,
                Q: '',
                A: 'B.  Es bedeutet, dass sie sich gegenseitig imponieren wollen und messen, wer der stärkere ist.'
            },
            {
                C: 5,
                Nr: 34,
                Q: '',
                A: 'C.  Auf diese Weise bedrohen sie sich gegenseitig.'
            },
            {
                C: 5,
                Nr: 34,
                Q: '',
                A: 'D.  Sie wollen miteinander spielen.'
            },
            {
                C: 5,
                Nr: 52,
                Q: 'Wie stellt man zwischen Mensch und Hund die Rangordnung klar?',
                A: ''
            },
            {
                C: 5,
                Nr: 52,
                Q: '',
                A: 'A.  Man wartet, bis der Hund ein Rangprivileg für sich in Anspruch nimmt oder in einer Übung einen Fehler macht und unterwirft ihn dann, indem man ihn mit Schwung auf den Rücken dreht und dort einen Moment lang festhält.'
            },
            {
                C: 5,
                Nr: 52,
                Q: '',
                A: 'B.  Man achtet darauf, dass man selbst derjenige ist, der zum größten Teil zu gemeinsamen Beschäftigungen auffordert.'
            },
            {
                C: 5,
                Nr: 52,
                Q: '',
                A: 'C.  Man ignoriert aufdringliches und forderndes Verhalten des Hundes.'
            },
            {
                C: 5,
                Nr: 52,
                Q: '',
                A: 'D.  Man isst demonstrativ vor den Augen des Hundes und gibt ihm von diesem Essen nichts ab.'
            },
            {
                C: 5,
                Nr: 70,
                Q: 'Was ist zu tun, wenn ein Hund, der immer lieb und friedlich war, ganz plötzlich aggressives Verhalten zeigt?',
                A: ''
            },
            {
                C: 5,
                Nr: 70,
                Q: '',
                A: 'A.  Der Hund sollte schnellstens dem Tierarzt vorgestellt werden, denn der Hund könnte Schmerzen oder eine Erkrankung haben.'
            },
            {
                C: 5,
                Nr: 70,
                Q: '',
                A: 'B.  Man sollte ihn sofort eindrücklich bestrafen, denn so etwas darf man nicht durchgehen lassen.'
            },
            {
                C: 5,
                Nr: 70,
                Q: '',
                A: 'C.  Gar nichts. Aggressives Verhalten ist ein normales Hundeverhalten.'
            },
            {
                C: 5,
                Nr: 70,
                Q: '',
                A: 'D.  Man sollte die Fütterung umstellen und mehr Kohlenhydrate füttern.'
            },
            {
                C: 6,
                Nr: 81,
                Q: 'Stimmt es, dass man älteren Hunden nichts mehr beibringen kann?',
                A: ''
            },
            {
                C: 6,
                Nr: 81,
                Q: '',
                A: 'A.  Ja, Hunde, die älter als ein Jahr sind, können nichts mehr lernen.'
            },
            {
                C: 6,
                Nr: 81,
                Q: '',
                A: 'B.  Nein, Hunde können ihr Leben lang neue Dinge lernen.'
            },
            {
                C: 6,
                Nr: 81,
                Q: '',
                A: 'C.  Nein, aber es ist einfacher, schon mit einem Welpen zu üben, dann gewöhnt sich der Hund nicht erst etwas Falsches an.'
            },
            {
                C: 6,
                Nr: 81,
                Q: '',
                A: 'D.  Nein. Da ein Welpe noch gar nichts lernen kann, sollte man überhaupt mit der Erziehung erst beginnen, wenn der Hund ein Jahr alt ist.'
            },
            {
                C: 6,
                Nr: 108,
                Q: 'Auf einer Wiese spielt eine Gruppe von Kindern Fußball. Wie verhalten Sie sich mit Ihrem frei laufenden Hund?',
                A: ''
            },
            {
                C: 6,
                Nr: 108,
                Q: '',
                A: 'A.  Wenn dies ein Hundeauslaufgebiet ist, darf ich den Hund frei laufen lassen. Ich erkläre den Fußballspielern das und schicke sie weg.'
            },
            {
                C: 6,
                Nr: 108,
                Q: '',
                A: 'B.  Ich muss gar nichts unternehmen, denn mein Hund ist nicht aggressiv. Für den Fall, dass er im Übermut den Ball kaputt machen sollte, habe ich eine Haftpflichtversicherung.'
            },
            {
                C: 6,
                Nr: 108,
                Q: '',
                A: 'C.  Ich leine den Hund vorsichtshalber an, bis ich an den Ball spielenden Kindern vorbei bin und sicher weiß, dass der Hund nicht zurücklaufen wird.'
            },
            {
                C: 6,
                Nr: 108,
                Q: '',
                A: 'D.  Man muss in solchen Situationen nur große Hunde anleinen, denn ein kleiner Hund kann einem Kind nicht gefährlich werden.'
            },
            {
                C: 6,
                Nr: 125,
                Q: 'Wieviel Bewegung braucht ein Hund?',
                A: ''
            },
            {
                C: 6,
                Nr: 125,
                Q: '',
                A: 'A.  Das ist abhängig von der Größe, dem Alter und dem Gesundheitszustand.'
            },
            {
                C: 6,
                Nr: 125,
                Q: '',
                A: 'B.  Hunde brauchen nicht viel Bewegung. Es sind Tiere, die Gemütlichkeit lieben.'
            },
            {
                C: 6,
                Nr: 125,
                Q: '',
                A: 'C.  Zu viel Bewegung schadet den Gelenken.'
            },
            {
                C: 6,
                Nr: 125,
                Q: '',
                A: 'D.  Das ist abhängig von der Fütterung.'
            },
            {
                C: 6,
                Nr: 153,
                Q: 'Darf man seinen Hund neben dem PKW herlaufen lassen?',
                A: ''
            },
            {
                C: 6,
                Nr: 153,
                Q: '',
                A: 'A.  Nur, wenn man es eilig hat.'
            },
            {
                C: 6,
                Nr: 153,
                Q: '',
                A: 'B.  Nein, das ist laut Straßenverkehrsordnung verboten.'
            },
            {
                C: 6,
                Nr: 153,
                Q: '',
                A: 'C.  Ja, wenn der Hund langsam daran gewöhnt wird.'
            },
            {
                C: 6,
                Nr: 153,
                Q: '',
                A: 'D.  Ja, aber nur auf Feldwegen.'
            },
            {
                C: 6,
                Nr: 164,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 6,
                Nr: 164,
                Q: '',
                A: 'A.  Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 6,
                Nr: 164,
                Q: '',
                A: 'B.  Der Hund ist stark ängstlich.'
            },
            {
                C: 6,
                Nr: 164,
                Q: '',
                A: 'C.  Der Hund ist aggressiv.'
            },
            {
                C: 6,
                Nr: 164,
                Q: '',
                A: 'D.  Der Hund ist unterwürfig'
            },
            {
                C: 7,
                Nr: 4,
                Q: 'Welche Dinge sind vor der Anschaffung eines Hundes wichtig?',
                A: ''
            },
            {
                C: 7,
                Nr: 4,
                Q: '',
                A: 'A.  Ist die Hundehaltung erlaubt?'
            },
            {
                C: 7,
                Nr: 4,
                Q: '',
                A: 'B.  Habe ich die Möglichkeit, den Hund 12-15 Jahre lang sicher zu behalten und zu versorgen?'
            },
            {
                C: 7,
                Nr: 4,
                Q: '',
                A: 'C.  Passt der ausgesuchte Hund von seiner Rasseveranlagung her tatsächlich zu meinem Lebensstil?'
            },
            {
                C: 7,
                Nr: 4,
                Q: '',
                A: 'D.  Die Abstammung von hochprämierten Elterntieren.'
            },
            {
                C: 7,
                Nr: 17,
                Q: 'Ist es schlimm, wenn der Hund im Welpenalter schon mit vielen Reizsituationen konfrontiert wird?',
                A: ''
            },
            {
                C: 7,
                Nr: 17,
                Q: '',
                A: 'A.  Nein, denn die im Welpenalter gemachten Erfahrungen haben prägenden Charakter. Hunde, die als Welpen in positiver Weise viele Reizsituationen erleben konnten, sind später selbstsicherer.'
            },
            {
                C: 7,
                Nr: 17,
                Q: '',
                A: 'B.  Ja, denn Welpen sind noch nicht so aufnahmefähig und sollten möglichst die ersten fünf Monate geschont werden.'
            },
            {
                C: 7,
                Nr: 17,
                Q: '',
                A: 'C.  Nein, denn ausreichend Erfahrungen im Welpenalter sind für eine optimale Entwicklung des Gehirns ausschlaggebend.'
            },
            {
                C: 7,
                Nr: 17,
                Q: '',
                A: 'D.  Ja, denn die Hunde, die als Welpen viel kennen gelernt haben, sind nervöser und aktiver und deshalb schwerer zu halten.'
            },
            {
                C: 7,
                Nr: 35,
                Q: 'Was für eine Bedeutung hat es, wenn sich ein Hund flach auf den Boden legt und einen entgegenkommenden Hund mit dem Blick fixiert?',
                A: ''
            },
            {
                C: 7,
                Nr: 35,
                Q: '',
                A: 'A.  Er möchte vermutlich einen ”Angriff” starten. Dieser Angriff kann spielerisch oder ernst ausgerichtet sein.'
            },
            {
                C: 7,
                Nr: 35,
                Q: '',
                A: 'B.  Er ist müde und möchte sich schnell noch ein wenig ausruhen, bis der andere Hund da ist.'
            },
            {
                C: 7,
                Nr: 35,
                Q: '',
                A: 'C.  Es hat gar nichts mit dem anderen Hund zu tun, sondern ist ein Zeichen von starken Bauchschmerzen.'
            },
            {
                C: 7,
                Nr: 35,
                Q: '',
                A: 'D.  Der liegende Hund verhält sich unterwürfig.'
            },
            {
                C: 7,
                Nr: 53,
                Q: 'Was zeigt eine gute Bindung zwischen Mensch und Hund an?',
                A: ''
            },
            {
                C: 7,
                Nr: 53,
                Q: '',
                A: 'A.  Der Hund kann mit seinem Menschen ausgelassen spielen.'
            },
            {
                C: 7,
                Nr: 53,
                Q: '',
                A: 'B.  Der Hund hat Spaß an Übungen, die ”sein” Mensch von ihm verlangt.'
            },
            {
                C: 7,
                Nr: 53,
                Q: '',
                A: 'C.  Wenn die Bezugspersonen häufig wechseln, lernt der Hund eine grundsätzlich gute Bindung gegenüber allen Menschen.'
            },
            {
                C: 7,
                Nr: 53,
                Q: '',
                A: 'D.  Ein Hund, der eine gute Bindung zu seinem Besitzer hat, orientiert sich auch auf dem Spaziergang häufig an ihm.'
            },
            {
                C: 7,
                Nr: 71,
                Q: 'Mein Hund hat beim Tierarzt auf dem Tisch sehr viel Angst. Er ist unruhig und zappelig. Manchmal knurrt er auch, wenn ihm etwas unangenehm ist. Ist es günstig, dem Hund gut zuzureden?',
                A: ''
            },
            {
                C: 7,
                Nr: 71,
                Q: '',
                A: 'A.  Ja, ich sollte möglichst die ganze Zeit mit dem Hund reden, um ihn zu beruhigen.'
            },
            {
                C: 7,
                Nr: 71,
                Q: '',
                A: 'B.  Nein, ich sollte gar nicht mit ihm reden, weil mein Hund lernen muss, mit derartigen Situationen alleine klar zu kommen.'
            },
            {
                C: 7,
                Nr: 71,
                Q: '',
                A: 'C.  Nein, ich sollte nur in den Momenten mit ihm reden, wenn er sich brav verhält und nicht knurrt.'
            },
            {
                C: 7,
                Nr: 71,
                Q: '',
                A: 'D.  Gut zureden ist nicht richtig. Statt dessen sollte man ihn einmal laut anschreien, damit er aufhört sich so aufzuführen.'
            },
            {
                C: 8,
                Nr: 82,
                Q: 'Wie kann man vermeiden, dass der Hund durch Strafen das Vertrauen in seinen Besitzer verliert?',
                A: ''
            },
            {
                C: 8,
                Nr: 82,
                Q: '',
                A: 'A.  Wenn man Ignorieren als Methode anwendet.'
            },
            {
                C: 8,
                Nr: 82,
                Q: '',
                A: 'B.  Bei einer indirekten Strafe, wie z.B. mit der Wasserpistole zu spritzen, wenn man dabei nicht gleichzeitig schimpft.'
            },
            {
                C: 8,
                Nr: 82,
                Q: '',
                A: 'C.  Bei einer indirekten Strafe, wie z.B. mit der Wasserpistole zu spritzen. Dabei sollte man gleichzeitig schimpfen, sonst versteht der Hund nicht, woher das Wasser kam.'
            },
            {
                C: 8,
                Nr: 82,
                Q: '',
                A: 'D.  Beim Schütteln am Nackenfell und gleichzeitigem Schimpfen, denn eine Hündin maßregelt auf diese Art und Weise auch ihre Welpen.'
            },
            {
                C: 8,
                Nr: 109,
                Q: 'Wie verhalten Sie sich, wenn Sie auf dem Hundespaziergang an einem Kinderspielplatz vorbeikommen?',
                A: ''
            },
            {
                C: 8,
                Nr: 109,
                Q: '',
                A: 'A.  Mein Hund liebt Kinder. Ich gucke, ob Kinder da sind, damit mein Hund mit den Kindern toben kann.'
            },
            {
                C: 8,
                Nr: 109,
                Q: '',
                A: 'B.  In der Nähe von Kinderspielplätzen leine ich meinen Hund an. Dadurch kann ich vermeiden, dass sich jemand belästigt oder gefährdet fühlt.'
            },
            {
                C: 8,
                Nr: 109,
                Q: '',
                A: 'C.  Wenn keine Kinder da sind, lasse ich den Hund laufen, denn er liebt es durch den Sand zu rennen.'
            },
            {
                C: 8,
                Nr: 109,
                Q: '',
                A: 'D.  Ich habe einen kleinen Hund, der keine Gefahr für Kinder darstellt. Deshalb lasse ich ihn einfach laufen.'
            },
            {
                C: 8,
                Nr: 126,
                Q: 'In welchem Bereich liegt die normale Körpertemperatur des Hundes?',
                A: ''
            },
            {
                C: 8,
                Nr: 126,
                Q: '',
                A: 'A.  Im After gemessen ca. 38 °C.'
            },
            {
                C: 8,
                Nr: 126,
                Q: '',
                A: 'B.  Im After gemessen ca. 36 °C.'
            },
            {
                C: 8,
                Nr: 126,
                Q: '',
                A: 'C.  Solange die Nase kühl und feucht ist, hat der Hund kein Fieber. Fiebermessen ist dann nicht nötig.'
            },
            {
                C: 8,
                Nr: 126,
                Q: '',
                A: 'D.  Ab einer Temperatur von 39,3 °C hat ein erwachsener Hund Fieber.'
            },
            {
                C: 8,
                Nr: 154,
                Q: 'Was ist zur Mitnahme von Hunden im Auto zu sagen? Kreuzen Sie die richtigen Aussagen an.',
                A: ''
            },
            {
                C: 8,
                Nr: 154,
                Q: '',
                A: 'A.  Der Hund sollte auf dem Beifahrersitz sitzen.'
            },
            {
                C: 8,
                Nr: 154,
                Q: '',
                A: 'B.  Der Hund sollte im Kofferraum transportiert werden.'
            },
            {
                C: 8,
                Nr: 154,
                Q: '',
                A: 'C.  Der Hund sollte im Auto gesichert transportiert werden.'
            },
            {
                C: 8,
                Nr: 154,
                Q: '',
                A: 'D.  Man kann den Hund z.B. in einer Transportbox, die auf dem Rücksitz befestigt ist, transportieren.'
            },
            {
                C: 8,
                Nr: 165,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 8,
                Nr: 165,
                Q: '',
                A: 'A.  Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 8,
                Nr: 165,
                Q: '',
                A: 'B.  Der Hund zeigt Beschwichtigungsverhalten.'
            },
            {
                C: 8,
                Nr: 165,
                Q: '',
                A: 'C.  Der Hund zeigt eine Spielaufforderung.'
            },
            {
                C: 8,
                Nr: 165,
                Q: '',
                A: 'D. Der Hund ist freundlich-unterwürfig.'
            },
            {
                C: 9,
                Nr: 5,
                Q: 'Welche Überlegungen muss man anstellen, wenn man sich einen Hund anschaffen will?',
                A: ''
            },
            {
                C: 9,
                Nr: 5,
                Q: '',
                A: 'A.  Der ausgewählte Hund sollte von seiner Rasseveranlagung her möglichst gut zu einem passen. Das Aussehen sollte hingegen nicht ausschlaggebend für die Entscheidung sein.'
            },
            {
                C: 9,
                Nr: 5,
                Q: '',
                A: 'B.  Beim Zusammenleben mit einem Hund könnten Probleme auftreten. Habe ich dann die Geduld, Zeit, Kraft mich darum zu kümmern?'
            },
            {
                C: 9,
                Nr: 5,
                Q: '',
                A: 'C.  Werde ich auch in den nächsten 12- 15 Jahren noch genug Zeit und Lust haben, einen Hund zu halten?'
            },
            {
                C: 9,
                Nr: 5,
                Q: '',
                A: 'D.  Habe ich ausreichend Geld für eine optimale Versorgung des Hundes, auch für medizinische Behandlungen?'
            },
            {
                C: 9,
                Nr: 18,
                Q: 'Ist es für die Entwicklung des Welpen sehr wichtig, ob er in seinen ersten Lebenswochen zahlreiche Außenreize kennenlernt?',
                A: ''
            },
            {
                C: 9,
                Nr: 18,
                Q: '',
                A: 'A.  Ja, denn je mehr Reize der Welpe kennen lernt, desto mehr Verknüpfungen der Nervenbahnen werden in seinem Gehirn angelegt.'
            },
            {
                C: 9,
                Nr: 18,
                Q: '',
                A: 'B.  Ja, denn vielfältige Reizsituationen geben dem Welpen Selbstvertrauen und Sicherheit im Umgang mit neuen Situationen.'
            },
            {
                C: 9,
                Nr: 18,
                Q: '',
                A: 'C.  Nein, denn ein Welpe kann noch gar keine Reize verarbeiten.'
            },
            {
                C: 9,
                Nr: 18,
                Q: '',
                A: 'D.  Nein, denn die Entwicklung des Gehirns hängt nicht vom Angebot verschiedener Reize ab, sondern geschieht automatisch.'
            },
            {
                C: 9,
                Nr: 36,
                Q: 'Was sind Stresssymptome eines Hundes?',
                A: ''
            },
            {
                C: 9,
                Nr: 36,
                Q: '',
                A: 'A.  Unruhiges Verhalten und Hecheln.'
            },
            {
                C: 9,
                Nr: 36,
                Q: '',
                A: 'B.  Futterbetteln.'
            },
            {
                C: 9,
                Nr: 36,
                Q: '',
                A: 'C.  Starkes Haaren und ggf. stumpfes Fell, bei länger anhaltendem Stress.'
            },
            {
                C: 9,
                Nr: 36,
                Q: '',
                A: 'D.  Nach vorne gerichtete Ohren und Interesse an der Umwelt.'
            },
            {
                C: 9,
                Nr: 54,
                Q: 'Welche Behandlungen können das Vertrauensverhältnis zwischen Hund und Halter schwächen?',
                A: ''
            },
            {
                C: 9,
                Nr: 54,
                Q: '',
                A: 'A.  Der Einsatz von direkten körperlichen Strafen.'
            },
            {
                C: 9,
                Nr: 54,
                Q: '',
                A: 'B.  Ein Maßregeln des Hundes wenn er in einer Situation unerwünschtes ängstliches Verhalten zeigt.'
            },
            {
                C: 9,
                Nr: 54,
                Q: '',
                A: 'C.  Viel Beschäftigung mit dem Hund.'
            },
            {
                C: 9,
                Nr: 54,
                Q: '',
                A: 'D.  Aus Hundesicht unlogisches Verhalten.'
            },
            {
                C: 9,
                Nr: 72,
                Q: 'Ist es ein Zeichen von Aggression, wenn ein Hund auf dem Spaziergang zu einer fremden Person hinrennt und diese unvermittelt anspringt?',
                A: ''
            },
            {
                C: 9,
                Nr: 72,
                Q: '',
                A: 'A.  Nicht unbedingt, aber es ist ein Verhalten, das man dem Hund frühzeitig abgewöhnen sollte, da es Leute gibt, die Angst vor Hunden haben.'
            },
            {
                C: 9,
                Nr: 72,
                Q: '',
                A: 'B.  Ja, Anspringen ist ein aggressives Verhalten.'
            },
            {
                C: 9,
                Nr: 72,
                Q: '',
                A: 'C.  Nein, das Anspringen ist als Spielaufforderung zu verstehen.'
            },
            {
                C: 9,
                Nr: 72,
                Q: '',
                A: 'D. Nein, es ist ein Zeichen großer Zuneigung.'
            },
            {
                C: 10,
                Nr: 83,
                Q: 'Nennen Sie Möglichkeiten, einen Hund zu belohnen.',
                A: ''
            },
            {
                C: 10,
                Nr: 83,
                Q: '',
                A: 'A.  Mit Futterhäppchen.'
            },
            {
                C: 10,
                Nr: 83,
                Q: '',
                A: 'B.  Mit Spielzeug bzw. einem Spiel.'
            },
            {
                C: 10,
                Nr: 83,
                Q: '',
                A: 'C.  Man sollte den Hund fest an sich drücken, ihm ins Ohr sagen, dass er brav war und ihn auf den Kopf küssen.'
            },
            {
                C: 10,
                Nr: 83,
                Q: '',
                A: 'D.  Man braucht einen Hund nicht extra zu belohnen, er weiß, dass er brav war, wenn er die Übung gut beherrscht.'
            },
            {
                C: 10,
                Nr: 110,
                Q: 'In welcher der folgenden Situationen ist es angebracht, den Hund an der Leine zu halten?',
                A: ''
            },
            {
                C: 10,
                Nr: 110,
                Q: '',
                A: 'A.  In der Innenstadt und an stark befahrenen Straßen.'
            },
            {
                C: 10,
                Nr: 110,
                Q: '',
                A: 'B.  Im Treppenhaus und auf Zugangswegen von Mehrfamilienhäusern.'
            },
            {
                C: 10,
                Nr: 110,
                Q: '',
                A: 'C.  In Hotels, in Läden oder in Restaurants.'
            },
            {
                C: 10,
                Nr: 110,
                Q: '',
                A: 'D.  In einem Hundeauslaufgebiet, wenn kein anderer Hund da ist, denn dann kann der Hund sowieso nicht spielen.'
            },
            {
                C: 10,
                Nr: 127,
                Q: 'Ist es sinnvoll, den Hund mit einem Mikrochip kennzeichnen zu lassen?',
                A: ''
            },
            {
                C: 10,
                Nr: 127,
                Q: '',
                A: 'A.  Ja, per Mikrochip kann der Hund immer sicher seinem Besitzer zugeordnet werden. Er ist unverwechselbar und nicht zu fälschen.'
            },
            {
                C: 10,
                Nr: 127,
                Q: '',
                A: 'B.  Ja. Die Daten eines Mikrochips, der nach den Iso-Richtlinien gefertigt ist, sind auch im Ausland lesbar.'
            },
            {
                C: 10,
                Nr: 127,
                Q: '',
                A: 'C.  Der Aufwand, den Hund mit einem Mikrochip zu kennzeichnen ist geringer als beim Tätowieren, weil die Narkose entfällt.'
            },
            {
                C: 10,
                Nr: 127,
                Q: '',
                A: 'D.  Nein, es ist nicht sinnvoll, da der Mikrochip gesundheitlich belastend ist.'
            },
            {
                C: 10,
                Nr: 155,
                Q: 'Welche Rechtsgebiete können für Hundehalter relevant sein?',
                A: ''
            },
            {
                C: 10,
                Nr: 155,
                Q: '',
                A: 'A.  Strafrecht, Zivilrecht und Ordnungswidrigkeitenrecht.'
            },
            {
                C: 10,
                Nr: 155,
                Q: '',
                A: 'B.  Kommunale Bestimmungen.'
            },
            {
                C: 10,
                Nr: 155,
                Q: '',
                A: 'C.  Tierschutzrecht.'
            },
            {
                C: 10,
                Nr: 155,
                Q: '',
                A: 'D.  Keines, man kann sich notfalls damit herausreden, dass man den Gesetzestext nicht kennt.'
            },
            {
                C: 10,
                Nr: 166,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 10,
                Nr: 166,
                Q: '',
                A: 'A.  Der Hund ist unsicher und leicht unterwürfig.'
            },
            {
                C: 10,
                Nr: 166,
                Q: '',
                A: 'B.  Der Hund ist freundlich-aufgeschlossen und aufmerksam.'
            },
            {
                C: 10,
                Nr: 166,
                Q: '',
                A: 'C.  Der Hund ist müde.'
            },
            {
                C: 10,
                Nr: 166,
                Q: '',
                A: 'D.  Der Hund ist aggressiv.'
            },
            {
                C: 11,
                Nr: 6,
                Q: 'Unter welchen Umständen sollte man davon absehen, sich einen Hund anzuschaffen?',
                A: ''
            },
            {
                C: 11,
                Nr: 6,
                Q: '',
                A: 'A.  Bei Berufstätigkeit, wenn der Hund mehr als sechs Stunden täglich alleine sein müsste.'
            },
            {
                C: 11,
                Nr: 6,
                Q: '',
                A: 'B.  Wenn absehbar ist, dass sich Berufs- oder Lebenssituation ändern werden und nicht sicher ist, ob Hundehaltung dann noch möglich ist.'
            },
            {
                C: 11,
                Nr: 6,
                Q: '',
                A: 'C.  Wenn man keinen Garten hat.'
            },
            {
                C: 11,
                Nr: 6,
                Q: '',
                A: 'D.  Wenn man eine starke Allergie auf Hundehaare hat.'
            },
            {
                C: 11,
                Nr: 19,
                Q: 'Welche Erfahrungen sind für ein reibungsloses Zusammenleben in der menschlichen Gesellschaft für einen Welpen wichtig?',
                A: ''
            },
            {
                C: 11,
                Nr: 19,
                Q: '',
                A: 'A.  Er sollte in positiven Begegnungen viele verschiedenen Menschen (von Babies bis zu alten Menschen) kennenlernen.'
            },
            {
                C: 11,
                Nr: 19,
                Q: '',
                A: 'B.  Die Teilnahme am Straßenverkehr sollte schrittweise geübt werden.'
            },
            {
                C: 11,
                Nr: 19,
                Q: '',
                A: 'C.  Welpen sollten möglichst viel im heimischen Bereich gehalten werden, damit sie nicht überfordert werden.'
            },
            {
                C: 11,
                Nr: 19,
                Q: '',
                A: 'D.  Aufenthalte im Zwinger, damit der Welpe lernen kann, auch einmal alleine zu bleiben.'
            },
            {
                C: 11,
                Nr: 37,
                Q: 'Woran erkennen Sie, dass Hunde miteinander spielen?',
                A: ''
            },
            {
                C: 11,
                Nr: 37,
                Q: '',
                A: 'A.  Sie zeigen gelegentlich eine Spielaufforderung.'
            },
            {
                C: 11,
                Nr: 37,
                Q: '',
                A: 'B.  Im Spiel jagt jeder Hund einmal einen anderen und wird selbst auch gejagt.'
            },
            {
                C: 11,
                Nr: 37,
                Q: '',
                A: 'C.  Im Spiel wird ein Hund in die Ecke getrieben oder umgeworfen. Der ”Unterlegene” quiekt hierbei laut auf, schnappt um sich und hat die Rute eingeklemmt.'
            },
            {
                C: 11,
                Nr: 37,
                Q: '',
                A: 'D.  Alles ist Spiel, wenn keine offenen Wunden entstehen.'
            },
            {
                C: 11,
                Nr: 55,
                Q: 'Ist es wichtig, mit einem Hund zu üben, dass er sich überall anfassen lässt?',
                A: ''
            },
            {
                C: 11,
                Nr: 55,
                Q: '',
                A: 'A.  Ja, es fördert das gegenseitige Vertrauen.'
            },
            {
                C: 11,
                Nr: 55,
                Q: '',
                A: 'B.  Ja, es erleichtert Pflegemaßnahmen.'
            },
            {
                C: 11,
                Nr: 55,
                Q: '',
                A: 'C.  Ja, Körperkontakte stärken die Bindung.'
            },
            {
                C: 11,
                Nr: 55,
                Q: '',
                A: 'D.  Nein, man muss so etwas nicht üben. Ein Hund, der gut untergeordnet ist, lässt sich sowieso überall problemlos anfassen.'
            },
            {
                C: 11,
                Nr: 73,
                Q: 'In welcher der genannten Situationen können Hunde aggressiv reagieren?',
                A: ''
            },
            {
                C: 11,
                Nr: 73,
                Q: '',
                A: 'A.  Wenn sie von einer fremden Person plötzlich angefasst werden und nicht ausweichen können.'
            },
            {
                C: 11,
                Nr: 73,
                Q: '',
                A: 'B.  Wenn man sie beim Fressen stört.'
            },
            {
                C: 11,
                Nr: 73,
                Q: '',
                A: 'C.  Beim Tierarzt bei schmerzhaften Manipulationen oder aus Angst.'
            },
            {
                C: 11,
                Nr: 73,
                Q: '',
                A: 'D.  Wenn man einem fremden Hund nicht in die Augen schaut.'
            },
            {
                C: 12,
                Nr: 84,
                Q: 'Gibt es Strafen, die man als ”artgerecht” bezeichnen kann?',
                A: ''
            },
            {
                C: 12,
                Nr: 84,
                Q: '',
                A: 'A.  Ja, Schläge, denn Hunde untereinander sind auch nicht zimperlich.'
            },
            {
                C: 12,
                Nr: 84,
                Q: '',
                A: 'B.  Ja, lautes Anschreien und gleichzeitiges leichtes Schlagen mit der Zeitung.'
            },
            {
                C: 12,
                Nr: 84,
                Q: '',
                A: 'C.  Ja, Ignorieren, wenn es die Situation zulässt.'
            },
            {
                C: 12,
                Nr: 84,
                Q: '',
                A: 'D.  Nein, Strafen können niemals ”artgerecht” sein'
            },
            {
                C: 12,
                Nr: 111,
                Q: 'Unter welchen Umständen kann ich meinen Hund in der Öffentlichkeit mit anderen Hunden spielen lassen?',
                A: ''
            },
            {
                C: 12,
                Nr: 111,
                Q: '',
                A: 'A.  Im Hundeauslaufgebiet immer'
            },
            {
                C: 12,
                Nr: 111,
                Q: '',
                A: 'B.  Wenn ich mit dem anderen Hundehalter abgeklärt habe, dass Spielkontakt erwünscht ist und beide Hunde frei laufen können.'
            },
            {
                C: 12,
                Nr: 111,
                Q: '',
                A: 'C.  Niemals an der Straße, an der Leine oder wenn sich andere Menschen oder Tiere durch die spielenden Hunde belästigt fühlen oder gefährdet werden könnten.'
            },
            {
                C: 12,
                Nr: 111,
                Q: '',
                A: 'D.  An der Straße nur, wenn die Hunde an der Leine sind. Sie könnten sonst beim Spielen auf die Fahrbahn laufen.'
            },
            {
                C: 12,
                Nr: 134,
                Q: 'Wann werden die meisten Hündinnen das erste Mal läufig?',
                A: ''
            },
            {
                C: 12,
                Nr: 134,
                Q: '',
                A: 'A. Wenn sie ausgewachsen sind.'
            },
            {
                C: 12,
                Nr: 134,
                Q: '',
                A: 'B. Zwischen 6 und 12 Monaten.'
            },
            {
                C: 12,
                Nr: 134,
                Q: '',
                A: 'C. Mit 18 Monaten.'
            },
            {
                C: 12,
                Nr: 134,
                Q: '',
                A: 'D. Wenn man sie von Junghundefutter auf Erwachsenennahrung umstellt'
            },
            {
                C: 12,
                Nr: 156,
                Q: 'Ist eine Haftpflichtversicherung für den Hund sinnvoll?',
                A: ''
            },
            {
                C: 12,
                Nr: 156,
                Q: '',
                A: 'A.  Ja, denn jeder Hund kann einen Schaden verursachen, für den sein Halter dann haftet.'
            },
            {
                C: 12,
                Nr: 156,
                Q: '',
                A: 'B.  Es ist im Tierschutzgesetz vorgeschrieben.'
            },
            {
                C: 12,
                Nr: 156,
                Q: '',
                A: 'C.  Ohne Haftpflichtversicherung darf der Hund nie frei laufen.'
            },
            {
                C: 12,
                Nr: 156,
                Q: '',
                A: 'D.  Es ist nicht sinnvoll, sondern eine unnötige Geldausgabe.'
            },
            {
                C: 12,
                Nr: 167,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 12,
                Nr: 167,
                Q: '',
                A: 'A.  Der Hund ist ängstlich und unterwürfig.'
            },
            {
                C: 12,
                Nr: 167,
                Q: '',
                A: 'B.  Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 12,
                Nr: 167,
                Q: '',
                A: 'C.  Der Hund droht unsicher und ist erregt.'
            },
            {
                C: 12,
                Nr: 167,
                Q: '',
                A: 'D.  Der Hund zeigt eine Unterwerfungsgeste.'
            },
            {
                C: 13,
                Nr: 7,
                Q: 'Welche Bedürfnisse des Hundes müssen bei artgerechter Haltung täglich ausreichend erfüllt werden?',
                A: ''
            },
            {
                C: 13,
                Nr: 7,
                Q: '',
                A: 'A.  Der Hund muss ausreichend, d.h. mehrere Stunden täglich geistig und körperlich gefordert werden.'
            },
            {
                C: 13,
                Nr: 7,
                Q: '',
                A: 'B.  Der Hund muss jeden Tag ausreichend lange und mehrmals täglich Sozialkontakte mit Menschen und Artgenossen haben.'
            },
            {
                C: 13,
                Nr: 7,
                Q: '',
                A: 'C. Der Hund muss täglich mindestens zwei Mahlzeiten erhalten.'
            },
            {
                C: 13,
                Nr: 7,
                Q: '',
                A: 'D. Der Hund sollte vorwiegend in einer Zwingeranlage mit gut isoliertem Boden gehalten werden.'
            },
            {
                C: 13,
                Nr: 23,
                Q: 'Wenn man einen Welpen kauft, sollte man .....',
                A: ''
            },
            {
                C: 13,
                Nr: 23,
                Q: '',
                A: 'A.  besonders in der ersten Phase viel Zeit (ggf. Urlaub) haben, um sich bestmöglich um den Hund kümmern zu können.'
            },
            {
                C: 13,
                Nr: 23,
                Q: '',
                A: 'B.  den Züchter vorher ”auf Herz und Nieren” geprüft haben, um einen Hund mit guten charakterlichen und genetischen Anlagen zu bekommen.'
            },
            {
                C: 13,
                Nr: 23,
                Q: '',
                A: 'C.  unbedingt einen Garten haben, denn sonst ist es sehr problematisch, den Hund stubenrein zu bekommen.'
            },
            {
                C: 13,
                Nr: 23,
                Q: '',
                A: 'D.  sicher sein, dass der Hund auch längerfristig zu dem Lebensstil und den Lebensumständen passt.'
            },
            {
                C: 13,
                Nr: 41,
                Q: 'Zwei Hunde kämpfen miteinander. Die Besitzer stehen daneben und schreien die Hunde an, um den Kampf zu beenden. Wie interpretieren die Hunde dieses Verhalten?',
                A: ''
            },
            {
                C: 13,
                Nr: 41,
                Q: '',
                A: 'A.  Durch das Anschreien bekommen die Hunde Angst und beenden den Kampf sofort.'
            },
            {
                C: 13,
                Nr: 41,
                Q: '',
                A: 'B.  Durch die aggressive Stimmung der Besitzer werden die Hunde angestachelt weiterzukämpfen.'
            },
            {
                C: 13,
                Nr: 41,
                Q: '',
                A: 'C.  Das Schreien der Besitzer beeinflusst das Verhalten der Hunde nicht.'
            },
            {
                C: 13,
                Nr: 41,
                Q: '',
                A: 'D.  Hunde interessieren sich nicht für das Verhalten von Menschen.'
            },
            {
                C: 13,
                Nr: 59,
                Q: 'Es kommt relativ häufig vor, dass Hunde Kinder im Gesicht verletzen. Warum?',
                A: ''
            },
            {
                C: 13,
                Nr: 59,
                Q: '',
                A: 'A.  Das Gesicht des Kindes ist in Schnauzenhöhe.'
            },
            {
                C: 13,
                Nr: 59,
                Q: '',
                A: 'B.  Kinder umarmen Hunde gerne und geben ihnen Küsse. Einigen Hunden ist diese Nähe zu viel und sie versuchen sich durch Schnappen aus der Situation zu befreien.'
            },
            {
                C: 13,
                Nr: 59,
                Q: '',
                A: 'C.  Die Gesichtsverletzungen entstehen meist nicht durch Bisse, sondern wenn die Kinder angesprungen werden und dabei hinfallen.'
            },
            {
                C: 13,
                Nr: 59,
                Q: '',
                A: 'D.  Hunde verletzen unbeabsichtigt gelegentlich das Gesicht eines Kindes, wenn sie über das ”Lefzenlecken” Beschwichtigung signalisieren wollen.'
            },
            {
                C: 13,
                Nr: 77,
                Q: 'Gibt es beim Üben mit einem ängstlichen Hund besondere Dinge zu bedenken?',
                A: ''
            },
            {
                C: 13,
                Nr: 77,
                Q: '',
                A: 'A.  Ja. Hunde können nur lernen, wenn sie entspannt sind und keine Angst haben.'
            },
            {
                C: 13,
                Nr: 77,
                Q: '',
                A: 'B.  Ja, man muss darauf achten, keine bedrohlichen Gesten in den Übungen zu verwenden.'
            },
            {
                C: 13,
                Nr: 77,
                Q: '',
                A: 'C.  Ja. Mit einem ängstlichen Hund sollte man lieber gar nicht trainieren, weil er aus Angst heraus beißen könnte.'
            },
            {
                C: 13,
                Nr: 77,
                Q: '',
                A: 'D.  Nein, mit einem ängstlichen Hund kann man trainieren, wie mit jedem anderen auch.'
            },
            {
                C: 14,
                Nr: 85,
                Q: 'Können im Zusammenhang mit Strafe Probleme auftreten?',
                A: ''
            },
            {
                C: 14,
                Nr: 85,
                Q: '',
                A: 'A.  Ja, der Hund kann Angst vor dem Hundeführer bekommen.'
            },
            {
                C: 14,
                Nr: 85,
                Q: '',
                A: 'B.  Ja, der Hund kann aggressiv werden, wenn er sich bedroht fühlt oder Schmerzen empfindet.'
            },
            {
                C: 14,
                Nr: 85,
                Q: '',
                A: 'C.  Ja. Wenn man im falschen Moment bestraft, kann der Hund die Verbindung zwischen Strafe und unerwünschtem Verhalten nicht herstellen'
            },
            {
                C: 14,
                Nr: 85,
                Q: '',
                A: 'D.  Nein, man braucht keine Probleme zu erwarten, denn Strafe ist etwas, was der Hund immer versteht.'
            },
            {
                C: 14,
                Nr: 115,
                Q: 'Wie verhalten Sie sich, wenn Ihnen ein Jogger entgegenkommt und Ihr Hund frei läuft?',
                A: ''
            },
            {
                C: 14,
                Nr: 115,
                Q: '',
                A: 'A.  Ich brauche nichts zu unternehmen, weil mein Hund höchstens zu dem Jogger hinläuft, ihn aber nicht belästigt oder beißt.'
            },
            {
                C: 14,
                Nr: 115,
                Q: '',
                A: 'B.  Ich rufe meinen Hund zu mir, leine ihn an und lasse ihn erst wieder los, wenn ich sicher weiß, dass er den Jogger nicht verfolgen wird.'
            },
            {
                C: 14,
                Nr: 115,
                Q: '',
                A: 'C.  Ich renne ein Stückchen mit dem Jogger mit. Das lenkt meinen Hund vom Jogger ab, denn er konzentriert sich dann nur auf mich.'
            },
            {
                C: 14,
                Nr: 115,
                Q: '',
                A: 'D.  Ich bitte den Jogger möglichst langsam zu laufen, um meinen Hund nicht zum Hinterher- rennen zu verleiten.'
            },
            {
                C: 14,
                Nr: 132,
                Q: 'Kann eine Hündin bei der ersten Läufigkeit schon erfolgreich gedeckt werden?',
                A: ''
            },
            {
                C: 14,
                Nr: 132,
                Q: '',
                A: 'A.  Ja.'
            },
            {
                C: 14,
                Nr: 132,
                Q: '',
                A: 'B.  Nein.'
            },
            {
                C: 14,
                Nr: 160,
                Q: 'Was geschieht im Falle eines Unfalls, wenn ein Hund ungesichert im Auto transportiert wird?',
                A: ''
            },
            {
                C: 14,
                Nr: 160,
                Q: '',
                A: 'A.  Er kann aus dem Fahrzeug geschleudert werden und weglaufen.'
            },
            {
                C: 14,
                Nr: 160,
                Q: '',
                A: 'B.  Eigentlich kann nichts Schlimmes passieren, da die Hunde ja zumeist im Auto liegen.'
            },
            {
                C: 14,
                Nr: 160,
                Q: '',
                A: 'C.  Der Hund kann bei einem Autounfall ein erhebliches Verletzungsrisiko für Insassen darstellen und auch selbst schwer verletzt werden.'
            },
            {
                C: 14,
                Nr: 160,
                Q: '',
                A: 'D.  Dem Fahrer kann unabhängig vom Unfallhergang eine Teilschuld zugesprochen werden.'
            },
            {
                C: 14,
                Nr: 168,
                Q: 'Welchen Ausdruck zeigt dieser Hund?',
                A: ''
            },
            {
                C: 14,
                Nr: 168,
                Q: '',
                A: 'A.  Der Hund ist ängstlich und unterwürfig.'
            },
            {
                C: 14,
                Nr: 168,
                Q: '',
                A: 'B.  Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 14,
                Nr: 168,
                Q: '',
                A: 'C.  Der Hund ist müde.'
            },
            {
                C: 14,
                Nr: 168,
                Q: '',
                A: 'D.  Der Hund droht unsicher und ist erregt.'
            },
            {
                C: 15,
                Nr: 8,
                Q: 'Nennen Sie Punkte, die man mindestens erfüllen muss, um einen Hund artgerecht zu halten.',
                A: ''
            },
            {
                C: 15,
                Nr: 8,
                Q: '',
                A: 'A.  Der Hund braucht täglich häufige Kontaktmöglichkeiten zu Menschen und/oder Hunden.'
            },
            {
                C: 15,
                Nr: 8,
                Q: '',
                A: 'B.  Hunde brauchen jederzeit freien Zugang zu Wasser.'
            },
            {
                C: 15,
                Nr: 8,
                Q: '',
                A: 'C.  Hunde brauchen ausreichend häufige (mind. dreimal täglich) und ausreichend lange (mind. zwei Stunden am Tag für einen gesunden Hund) Spaziergänge.'
            },
            {
                C: 15,
                Nr: 8,
                Q: '',
                A: 'D.  Es muss gewährleistet sein, dass der Hund im Krankheitsfall medizinisch versorgt werden kann.'
            },
            {
                C: 15,
                Nr: 24,
                Q: 'Welche Dinge sprechen gegen den Erwerb eines Welpen aus dieser Quelle?',
                A: ''
            },
            {
                C: 15,
                Nr: 24,
                Q: '',
                A: 'A.  Die Hündin verbellt jeden, der in die Nähe kommt, und die Welpen bellen oder verstecken sich.'
            },
            {
                C: 15,
                Nr: 24,
                Q: '',
                A: 'B.  Die Hunde haben keine Papiere.'
            },
            {
                C: 15,
                Nr: 24,
                Q: '',
                A: 'C.  Die Hunde sind schmuddelig, weil sie im Laub spielen.'
            },
            {
                C: 15,
                Nr: 24,
                Q: '',
                A: 'D.  Die Welpen rennen zu jedem hin.'
            },
            {
                C: 15,
                Nr: 41,
                Q: 'Warum reagieren viele Hunde an der Leine aggressiver?',
                A: ''
            },
            {
                C: 15,
                Nr: 41,
                Q: '',
                A: 'A.  Hunde an der Leine sind mutiger.'
            },
            {
                C: 15,
                Nr: 41,
                Q: '',
                A: 'B.  Hunde können sich an der Leine nicht frei bewegen und ausweichen und fühlen sich schneller bedroht.'
            },
            {
                C: 15,
                Nr: 41,
                Q: '',
                A: 'C.  Hunde haben dieses Verhalten als Strategie gelernt, um Situationen, die sie ängstigen, schneller beenden oder für sich entscheiden zu können.'
            },
            {
                C: 15,
                Nr: 41,
                Q: '',
                A: 'D.  Hunde ärgern sich darüber, dass sie angeleint sind und übertragen ihre Wut auf den anderen Hund.'
            },
            {
                C: 15,
                Nr: 60,
                Q: 'Ist es eine Frage des Alters eines Kindes, ob das Zusammenleben mit einem Hund reibungslos funktioniert?',
                A: ''
            },
            {
                C: 15,
                Nr: 60,
                Q: '',
                A: 'A.  Nein, es ist eine Frage der Gewöhnung, ob der Hund Kinder einer bestimmten Altersklasse akzeptiert oder nicht.'
            },
            {
                C: 15,
                Nr: 60,
                Q: '',
                A: 'B.  Nein, das hat mit dem Alter nichts zu tun. Ein Hund fühlt sich innerhalb der Familie in jedem Fall rangniedriger als die Kinder.'
            },
            {
                C: 15,
                Nr: 60,
                Q: '',
                A: 'C.  Indirekt ja, denn reifere Jugendliche werden von vielen Hunden als Erwachsene eingestuft.'
            },
            {
                C: 15,
                Nr: 60,
                Q: '',
                A: 'D.  Ja. Das Zusammenleben zwischen kleinen Kindern und Hunden ist immer problematisch.'
            },
            {
                C: 15,
                Nr: 78,
                Q: 'Innerhalb welcher Zeit kann ein Hund eine Belohnung sicher mit seiner gezeigten Handlung verknüpfen?',
                A: ''
            },
            {
                C: 15,
                Nr: 78,
                Q: '',
                A: 'A.  Es dürfen nicht mehr als eine, allerhöchstens zwei Sekunden vergehen.'
            },
            {
                C: 15,
                Nr: 78,
                Q: '',
                A: 'B.  Man sollte den Hund innerhalb von fünf Sekunden belohnen.'
            },
            {
                C: 15,
                Nr: 78,
                Q: '',
                A: 'C.  Es ist nicht von der Zeit abhängig, ob der Hund die Übung begreift, sondern nur von der Tatsache, ob die Futterbelohnung lecker genug ist.'
            },
            {
                C: 15,
                Nr: 78,
                Q: '',
                A: 'D.  Man hat ein paar Minuten Zeit, besonders wenn der Hund die Handlung länger zeigt.'
            },
            {
                C: 16,
                Nr: 86,
                Q: 'Was passiert, wenn man versucht, einen Hund, der gerade Angst hat, mit Worten und durch Streicheln zu beruhigen?',
                A: ''
            },
            {
                C: 16,
                Nr: 86,
                Q: '',
                A: 'A.  Der Hund wird sich beruhigen und seine Angst verlieren.'
            },
            {
                C: 16,
                Nr: 86,
                Q: '',
                A: 'B.  Der Hund wird darin bestätigt, dass es sich lohnt, Angst zu haben. Man verschlimmert die Angst.'
            },
            {
                C: 16,
                Nr: 86,
                Q: '',
                A: 'C.  Man verschlimmert die Angst, denn Hunde untereinander würden sich nicht beruhigen. Die plötzliche Aufmerksamkeit des Besitzers zeigt dem Hund, dass dieser auch eine Unsicherheit verspürt.'
            },
            {
                C: 16,
                Nr: 86,
                Q: '',
                A: 'D.  Der Hund könnte aggressiv reagieren.'
            },
            {
                C: 16,
                Nr: 116,
                Q: 'Wer ist für das Entfernen von Hundekot verantwortlich?',
                A: ''
            },
            {
                C: 16,
                Nr: 116,
                Q: '',
                A: 'A.  Die Städte, denn dafür wird Hundesteuer bezahlt.'
            },
            {
                C: 16,
                Nr: 116,
                Q: '',
                A: 'B.  Der Halter.'
            },
            {
                C: 16,
                Nr: 116,
                Q: '',
                A: 'C.  Die Allgemeinheit. Jeder, der einen Hundehaufen sieht, muss ihn entfernen.'
            },
            {
                C: 16,
                Nr: 116,
                Q: '',
                A: 'D.  Niemand. Hundekot muss nicht entfernt werden, denn es ist etwas Natürliches, mit dem man leben muss.'
            },
            {
                C: 16,
                Nr: 133,
                Q: 'Nennen Sie einige Parasiten, die auch in Deutschland sehr häufig vorkommen.',
                A: ''
            },
            {
                C: 16,
                Nr: 133,
                Q: '',
                A: 'A.  Zecken.'
            },
            {
                C: 16,
                Nr: 133,
                Q: '',
                A: 'B.  Milben.'
            },
            {
                C: 16,
                Nr: 133,
                Q: '',
                A: 'C.  Flöhe.'
            },
            {
                C: 16,
                Nr: 133,
                Q: '',
                A: 'D.  Herzwürmer.'
            },
            {
                C: 16,
                Nr: 161,
                Q: 'Gibt es gesetzliche Vorschriften für die Zwingerhaltung von Hunden?',
                A: ''
            },
            {
                C: 16,
                Nr: 161,
                Q: '',
                A: 'A.  Nein.'
            },
            {
                C: 16,
                Nr: 161,
                Q: '',
                A: 'B.  Ja, es gibt eine Tierschutz-Hundehaltungs-Verordnung.'
            },
            {
                C: 16,
                Nr: 161,
                Q: '',
                A: 'C.  Ja, sie besagen, dass nur Hunde, die größer als 40 cm Schulterhöhe sind, in Zwingeranlagen gehalten werden dürfen.'
            },
            {
                C: 16,
                Nr: 161,
                Q: '',
                A: 'D.  Ja, der Hund darf nicht länger als 2 Stunden täglich im Zwinger gehalten werden.'
            },
            {
                C: 16,
                Nr: 169,
                Q: 'Welchen Ausdruck zeigt dieser Hund?               ',
                A: ''
            },
            {
                C: 16,
                Nr: 169,
                Q: '',
                A: 'A.  Der Hund ist ängstlich und unterwürfig.'
            },
            {
                C: 16,
                Nr: 169,
                Q: '',
                A: 'B.  Der Hund ist neutral bis aufmerksam.'
            },
            {
                C: 16,
                Nr: 169,
                Q: '',
                A: 'C.  Der Hund ist müde.'
            },
            {
                C: 16,
                Nr: 169,
                Q: '',
                A: 'D. Der Hund zeigt eine Unterwerfungsgeste.'
            }
        ],
        model: 'HSK.model.Frage',
        storeId: 'Fragen',
        proxy: {
            type: 'memory',
            reader: {
                type: 'json'
            }
        }
    }
});