/*
 * File: app/store/Korrekt.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HSK.store.Korrekt', {
    extend: 'Ext.data.Store',

    requires: [
        'HSK.model.Korrekt',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    config: {
        data: [
            {
                Q: 1,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 14,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 32,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 50,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 68,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 79,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 106,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 123,
                A1: 'A',
                A2: 'B',
                A3: 'D',
                A4: ''
            },
            {
                Q: 151,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 162,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 2,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 15,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 33,
                A1: 'D',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 51,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 69,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 80,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 107,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 124,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 152,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 163,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 3,
                A1: 'A',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 16,
                A1: 'A',
                A2: 'C',
                A3: 'D',
                A4: ''
            },
            {
                Q: 34,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 52,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 70,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 81,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 108,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 125,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 153,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 164,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 4,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 17,
                A1: 'A',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 35,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 53,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 71,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 82,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 109,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 126,
                A1: 'A',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 154,
                A1: 'C',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 165,
                A1: 'B',
                A2: 'D',
                A3: '',
                A4: ''
            },
            {
                Q: 5,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: 'D'
            },
            {
                Q: 18,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 36,
                A1: 'A',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 54,
                A1: 'A',
                A2: 'B',
                A3: 'D',
                A4: ''
            },
            {
                Q: 72,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 83,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 110,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 127,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 155,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 166,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 6,
                A1: 'A',
                A2: 'B',
                A3: 'D',
                A4: ''
            },
            {
                Q: 19,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 37,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 55,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 73,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 84,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 111,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 134,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 156,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 167,
                A1: 'C',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 7,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 23,
                A1: 'A',
                A2: 'B',
                A3: 'D',
                A4: ''
            },
            {
                Q: 41,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 59,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 77,
                A1: 'A',
                A2: 'B',
                A3: '',
                A4: ''
            },
            {
                Q: 85,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 115,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 132,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 160,
                A1: 'A',
                A2: 'C',
                A3: 'D',
                A4: ''
            },
            {
                Q: 168,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 8,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: 'D'
            },
            {
                Q: 24,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 41,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 60,
                A1: 'A',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 78,
                A1: 'A',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 86,
                A1: 'B',
                A2: 'C',
                A3: '',
                A4: ''
            },
            {
                Q: 116,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 133,
                A1: 'A',
                A2: 'B',
                A3: 'C',
                A4: ''
            },
            {
                Q: 161,
                A1: 'B',
                A2: '',
                A3: '',
                A4: ''
            },
            {
                Q: 169,
                A1: 'A',
                A2: 'D',
                A3: '',
                A4: ''
            }
        ],
        model: 'HSK.model.Korrekt',
        storeId: 'Korrekt',
        proxy: {
            type: 'memory',
            reader: {
                type: 'json'
            }
        }
    }
});