/*
 * File: app/store/Navigation.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HSK.store.Navigation', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'HSK.model.Navigation',
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json'
    ],

    config: {
        data: [
            {
                text: 'Fragebögen',
                items: [
                    {
                        text: 'Fragebogen 1',
                        type: 'sheet',
                        nr: 1,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 2',
                        type: 'sheet',
                        nr: 2,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 3',
                        type: 'sheet',
                        nr: 3,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 4',
                        type: 'sheet',
                        nr: 4,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 5',
                        type: 'sheet',
                        nr: 5,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 6',
                        type: 'sheet',
                        nr: 6,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 7',
                        type: 'sheet',
                        nr: 7,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 8',
                        type: 'sheet',
                        nr: 8,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 9',
                        type: 'sheet',
                        nr: 9,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 10',
                        type: 'sheet',
                        nr: 10,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 11',
                        type: 'sheet',
                        nr: 11,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 12',
                        type: 'sheet',
                        nr: 12,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 13',
                        type: 'sheet',
                        nr: 13,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 14',
                        type: 'sheet',
                        nr: 14,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 15',
                        type: 'sheet',
                        nr: 15,
                        leaf: true
                    },
                    {
                        text: 'Fragebogen 16',
                        type: 'sheet',
                        nr: 16,
                        leaf: true
                    }
                ]
            },
            {
                text: 'Zufallsfrage',
                type: 'random',
                leaf: true,
                
            },
            {
                text: 'Verbessern',
                type: 'learn',
                leaf: true
            }
        ],
        model: 'HSK.model.Navigation',
        storeId: 'Navigation',
        defaultRootProperty: 'items',
        proxy: {
            type: 'memory',
            reader: {
                type: 'json'
            }
        }
    }
});