/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Frage',
        'Navigation',
        'Korrekt'
    ],
    stores: [
        'Fragen',
        'Navigation',
        'Korrekt'
    ],
    views: [
        'Main',
        'Details'
    ],
    controllers: [
        'QnA'
    ],
    name: 'HSK',

    launch: function() {

        Ext.create('HSK.view.Main', {fullscreen: true});
    }

});
